name: rnaseq
channels:
  - conda-forge
  - base
  - R
  - bioconda
  - defaults
dependencies:
  - samtools=1.16.1
  - python=3.9
  - hisat2=2.2.1
  - gffcompare=0.12.6
  - stringtie=2.2.1
  - agat=1.0.0
  - regtools=1.0.0
  - r-base=4.2.2
  - r-tidyverse=1.3.2
  - r-devtools=2.4.5
  - r-glue=1.6.2
  - r-patchwork=1.1.2
  - r-ggsci=2.9
  - r-ggtext=0.1.2
  - r-here=1.0.1
  - r-tinytex=0.44
  - r-kableExtra=1.3.4
  - r-gt=0.9.0
  - snakemake=7.24.0
