name: rnaseq
channels:
  - conda-forge
  - base
  - R
  - bioconda
  - defaults
dependencies:
  - samtools=1.16
  - python=3.9
  - hisat2=2.2.1
  - gffcompare=0.12.6
  - stringtie=2.2.1
  - agat=1.0.0
  - r-base=4.2.2
  - r-tidyverse=1.3.2
  - r-devtools
