name: thev_rnaseq
channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults
dependencies:
  - samtools
  - python
  - hisat2
  - gffcompare
  - stringtie
  - agat
  - regtools
  - r-base
  - r-tidyverse
  - r-devtools
  - r-glue
  - r-patchwork
  - r-ggsci
  - r-ggtext
  - r-english
  - r-tinytex
  - r-plyr
  - r-rticles
  - r-flextable
  - r-officedown
  - bioconductor-ballgown
  - bioconductor-biocinstaller
  - bioconductor-GenomicRanges
  - bioconductor-genefilter
  - bioconductor-GenomicAlignments
  - snakemake
  - graphviz